export const ACTIONS = {
  UPDATE_BACKGROUND: "UPDATE_BACKGROUND",
  UPDATE_TEXT: "UPDATE_TEXT",
  CLEAR_TO_LOGO: "CLEAR_TO_LOGO",
  PLAY: "PLAY",
  PAUSE: "PAUSE",
  TOGGLE_PLAY_PAUSE: "TOGGLE_PLAY_PAUSE",
  SKIP_FORWARD: "SKIP_FORWARD",
  SKIP_BACKWARDS: "SKIP_BACKWARDS",
  SET_CURRENT_TIME: "SET_CURRENT_TIME",
  SEEK: "SEEK",
  SET_PROJECTOR: "SET_PROJECTOR",
};
